### ISSUE TITLE
add utility to split bufr files by subsets.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS-bufr#89]
The bufr files in the "dump" are a result of the `dumpjb` step.  Several bufr operations occur in this step; one of which is combining bufr files from the "tank" into a single bufr file in the "dump".  This is done by the obsprocessing code `combfr.f`.

`combfr.f` is a generic bufr utility that concatenates a number of bufr files into a single one and would ideally reside in NCEPLIBS-bufr. 

This issue relates to adding a utility to split the "dump" bufr file into its subsets, so that they can be read in by the DA framework of JEDI.
When the DA framework reads bufr files straight from the "tank", this utility won't be used (although may still be useful).

**Comment by jack-woollen** [comment]
1) There's some issue here with nomenclature in comments concerning the distinction between a message type/subtype and a subset. A message type/subtype (lets say MTS for short) combination defines a subset template. For example the tag NC005064 is an MTS which will contain subsets defined by elements, operators and sequences found in bufr tables a, b, c, and d for that MTS . Each MTS file usually contains many subsets. The code here collates messages from a bufr file in its MTS components. Its mostly my fault and I should fix it.
2) I wonder why the test failed. I can guess that maybe the exemplar might have slightly different fortran control words for unformatted files or something like that. Are the files being compared available somewhere I could llok at them?

**Comment by aerorahul** [comment]
@jack-woollen 
re. 2  The `split_by_subset.x` test fails because we have not uploaded the test files to the ftp directory.  Once it is uploaded, the test will pass.

My `bufr` is weak, so I don't fully understand the language.  I think what you are suggesting here is that this program is actually; `split_by_MTS` rather than `split_by_subset`.  subsets are still present in the split files.  Thanks for the clarification.  May be I should rename this to `split_by_MTS` or something else other than `subset`.

**Comment by jack-woollen** [comment]
It could be split_by_subset_type. I'd like to change some of the comments as well.

**Comment by aerorahul** [comment]
@jack-woollen 
Feel free to clone the branch and commit to it.

**Comment by jack-woollen** [comment]
@aerorahul  Will do.
